### ISSUE TITLE
Invalid request: v (version) is required

### ISSUE THREAD

**Issue by dmtrkzntsv** [artfultom/whom-i-know#3]
The service couldn't get information about user (when you filled id)

Example:
[https://api.vk.com/method/users.get?uids=durov&fields=sex,bdate,photo_100,education&callback=jQuery21309576818257999609_1520067547972&_=1520067547986](https://api.vk.com/method/users.get?uids=durov&fields=sex,bdate,photo_100,education&callback=jQuery21309576818257999609_1520067547972&_=1520067547986)

**Comment by artfultom** [comment]
The special parameter "v=fuckvk" was added
